<a href="https://colab.research.google.com/github/AarnoStormborn/Deep-Learning-with-PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Started with PyTorch

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


## Introduction to Tensors

### Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar, scalar.item()

(tensor(7), 7)

In [3]:
scalar.ndim

0

In [4]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

### Creating Random Tensors

In [13]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3005, 0.7461, 0.6613, 0.5407],
        [0.4221, 0.5411, 0.1214, 0.5613],
        [0.1842, 0.3188, 0.8360, 0.8784]])

In [14]:
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor.ndim

3

### Zeros & Ones

In [15]:
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

### Range of Tensors

In [18]:
step_tensor = torch.arange(start=0, end=100, step=4)

In [19]:
step_tensor

tensor([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68,
        72, 76, 80, 84, 88, 92, 96])

In [20]:
zeros = torch.zeros_like(step_tensor)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])

### Tensor datatypes

3 common errors with PyTorch Datatypes
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [21]:
# float_32_tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,   # Tensor Datatype
                               device=None, # Define where the computations occur  cpu/cuda
                               requires_grad=False) # whether or not to track gradients

In [22]:
float_32_tensor.dtype

torch.float32

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [24]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Tensor Operations

In [26]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [27]:
tensor * 10

tensor([10, 20, 30])

In [28]:
tensor - 10

tensor([-9, -8, -7])

In [29]:
# PyTorch Inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [30]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [31]:
torch.add(1,1)

tensor(2)

### Matrix Multiplication

Two ways of performing Multiplcation
1. Element-wise multiplication
2. Matrix Multiplication (dot product)

In [32]:
# Element wise multiplication

tensor * tensor

tensor([1, 4, 9])

In [33]:
# Matrix Multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [34]:
one_tensor = torch.rand(3,4)

In [35]:
torch.matmul(one_tensor, one_tensor.T)

tensor([[0.2581, 0.2578, 0.4778],
        [0.2578, 1.1275, 1.1936],
        [0.4778, 1.1936, 1.7867]])

In [36]:
one_tensor @ one_tensor.T

tensor([[0.2581, 0.2578, 0.4778],
        [0.2578, 1.1275, 1.1936],
        [0.4778, 1.1936, 1.7867]])

### Tensor Aggregation

In [37]:
x = torch.arange(0, 100, 5)

In [38]:
# min
torch.min(x)

tensor(0)

In [39]:
# max
torch.max(x)

tensor(95)

In [40]:
# mean
torch.mean(x.type(torch.float32))

tensor(47.5000)

In [41]:
torch.sum(x), x.sum()

(tensor(950), tensor(950))

### Positional Min Max

In [42]:
# Positional min
torch.argmin(x)

tensor(0)

In [43]:
# Positional max
torch.argmax(x)

tensor(19)

In [44]:
some_tensor = torch.tensor([[2,3,9],
                            [5,6,4],
                            [7,8,1]])

In [45]:
torch.argmin(some_tensor, dim=1)  # Minimum in each row

tensor([0, 2, 2])

In [46]:
torch.argmax(some_tensor, dim=0) # Maximum in each column

tensor([2, 2, 0])

### Reshaping, Stacking, Squeezing

* Reshape - reshape tensor
* View - return view of tensor
* Stacking - combine multiple tensors (vertical/horizontal stacking)
* Squeeze - remove `1` dimension
* Unsqueeze - add `1` dimension

In [47]:
import torch

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [48]:
# Reshape

x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [49]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

**Note**: `reshape()` is like Deep Copy, `view()` is like Shallow Copy

In [50]:
# Squeeze

x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [51]:
# Stack tensors
x_stacked_0 = torch.stack([x,x,x,x], dim=0)  # dim=0 means Vertical Stacking
x_stacked_0

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [52]:
x_stacked_1 = torch.stack([x,x,x,x], dim=1)  # dim=1 means Horizontal Stacking
x_stacked_1

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [53]:
# Unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
x_squeezed, x_unsqueezed

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [55]:
# Permute

x_original = torch.rand(size=(224,224,3))
x_permuted = torch.permute(x_original, (2,0,1))

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [56]:
# Get Numpy array from tensor
x.numpy()

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [57]:
# Get Python list from tensor
x.tolist()

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

### Indexing

In [58]:
import torch

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [59]:
x[0, 1, 2]

tensor(6)

In [60]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
x[0, 2]

tensor([7, 8, 9])

In [62]:
x[:, 0]

tensor([[1, 2, 3]])

In [63]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [64]:
x[:, 1, 1]

tensor([5])

## PyTorch Tensors & Numpy

In [65]:
import torch
import numpy as np

In [66]:
array = np.arange(1., 8.)  # Numpy default dtype is float64
tensor = torch.from_numpy(array).type(torch.float32)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [67]:
# Change value of array
array[0] = 4.

In [68]:
# Tensor remains unchanged
array, tensor

(array([4., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

## PyTorch Reproducibility

In [69]:
# Always different values

torch.rand(3,3), torch.rand(3,3)

(tensor([[0.8323, 0.8379, 0.5781],
         [0.9763, 0.0189, 0.6592],
         [0.3201, 0.0012, 0.4960]]),
 tensor([[0.7293, 0.0805, 0.1275],
         [0.0592, 0.6727, 0.9537],
         [0.9237, 0.1132, 0.6928]]))

In [70]:
# Random but Reproducible

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
print(torch.rand(3,3))

torch.manual_seed(RANDOM_SEED)
print(torch.rand(3,3))

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


## Running PyTorch on GPUs

In [71]:
!nvidia-smi

Sat Nov 11 10:21:55 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [72]:
import torch
torch.cuda.is_available()

True

## Setting up Device Agnostic code

In [73]:
# Set device variable

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [74]:
# Create tensor

tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [75]:
# Move tensor to GPU

tensor_gpu = tensor.to(device)
tensor.device, tensor_gpu.device

(device(type='cpu'), device(type='cuda', index=0))

In [77]:
# Move tensor to CPU

tensor_gpu.cpu().numpy()

array([1, 2, 3])

In [78]:
tensor_gpu

tensor([1, 2, 3], device='cuda:0')